# Copyright 2020 The MathWorks, Inc.

name: Run MATLAB Command
description: >-
  Run MATLAB scripts, functions, and statements
inputs:
  command:
    description: >-
      Script, function, or statement to execute
    required: true
  startup-options:
    description: >-
      Startup options for MATLAB
    required: false
    default: ""
runs:
  using: node16
  main: dist/index.js
